import React from "react"

// "footer_notice": "THERE MAY BE A RISK ASSOCIATED WITH CONSUMING RAW SHELLFISH AS IS THE CASE <br>WITH OTHER RAW PROTEIN PRODUCTS. PLEASE CONSUME AT YOUR OWN RISK**",
// "footer_notice2": "THE PRODUCTS WITH AN INDICATED PRICE ARE NOT INCLUDED IN THE ALL-INCLUSIVE<br>PACKAGE AND ARE PRICED IN MEXICAN PESOS, INCLUSING IVA**",